name = "cpp11"
entrypoint = "main.cpp"
extensions = [
  "cpp",
  "cc",
]
packages = [
  "clang-7",
  "clang-format-7"
]
setup = [
  "cd /tmp && wget -q https://github.com/cquery-project/cquery/releases/download/v20180302/cquery-v20180302-x86_64-unknown-linux-gnu.tar.xz && tar xf cquery-v20180302-x86_64-unknown-linux-gnu.tar.xz && cd cquery-v20180302-x86_64-unknown-linux-gnu && cp bin/cquery /bin && cp -r lib/* /lib/ && cd /tmp && rm cquery-v20180302-x86_64-unknown-linux-gnu.tar.xz && rm -r cquery-v20180302-x86_64-unknown-linux-gnu",
  "update-alternatives --install /usr/bin/clang-format clang-format `which clang-format-7` 100",
]

[compile]
command = [
  "clang++-7",
  "-pthread",
  "-std=c++11",
  "-o",
  "main"
]

[run]
command = [
  "./main"
]

[tests]

  [tests.hello]
  code = "#include <iostream>\nint main() { std::cout << \"hello\" << std::endl; }"
  output = "hello\n"

[languageServer]
command = [
  "cquery",
  "--init={\"progressReportFrequencyMs\": -1,\"cacheDirectory\":\"/tmp/cquery\", \"extraClangArguments\": [\"-std=c++11\", \"-pthread\"]}"
]
