name = "fortran"
entrypoint = "main.f90"
extensions = [
  "f90"
]
packages = [
  "gfortran"
]
setup = [
]

[compile]
command = [
  "bash",
  "-c",
  "gfortran main.f90"
]

[run]
command = [
  "./a.out"
]

[tests]

  [tests.hello]
  code = "program main\nprint '(\"hello\")'\nend program main"
  output = "hello\n"
